stages:
  - assemble
  - test

assemble:
  image: gradle:latest
  stage: assemble
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  image: gradle:latest
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - assemble
  artifacts:
    paths:
      - build/libs/*.jar
      
after_script:
  - echo "End CI"
